Tailorized "2004-01-19 15:44:53 by logg" Fix configure option --disable-curses

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -862,6 +862,7 @@ Optional Features:
                           Turn on debugging and warnings
   --disable-curses
                           Compile without curses
+  --enable-bmp            support loading BMP images default=yes
 
 Some influential environment variables:
   CC
@@ -1645,15 +1646,26 @@ fi
 # Check whether --enable-debug or --disable-debug was given.
 if test "${enable_debug+set}" = set; then
   enableval="$enable_debug"
-  CXXFLAGS='-DDEBUG=1 -g -O2 -Wall -Werror'
+  enable_debug=yes
 fi;
 
 # Option --disable-curses
 # Check whether --enable-curses or --disable-curses was given.
 if test "${enable_curses+set}" = set; then
   enableval="$enable_curses"
-  CXXFLAGS=$CXXFLAGS' -DNO_CURSES=1'
+  enable_curses=no
 fi;
+
+# Check whether --enable-bmp or --disable-bmp was given.
+if test "${enable_bmp+set}" = set; then
+  enableval="$enable_bmp"
+
+else
+  enable_bmp=yes
+fi;
+if test x$enable_bmp = xyes; then
+    CFLAGS="$CFLAGS -DLOAD_BMP"
+fi
 
 # Checks for programs
 ac_ext=c
@@ -3872,56 +3884,14 @@ _ACEOF
 fi
 
 
-# Check for libxml2
-# Extract the first word of "xml2-config", so it can be a program name with args.
-set dummy xml2-config; ac_word=$2
-echo "$as_me:$LINENO: checking for $ac_word" >&5
-echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6
-if test "${ac_cv_prog_libxml2_found+set}" = set; then
-  echo $ECHO_N "(cached) $ECHO_C" >&6
-else
-  if test -n "$libxml2_found"; then
-  ac_cv_prog_libxml2_found="$libxml2_found" # Let the user override the test.
-else
-as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
-for as_dir in $PATH
-do
-  IFS=$as_save_IFS
-  test -z "$as_dir" && as_dir=.
-  for ac_exec_ext in '' $ac_executable_extensions; do
-  if $as_executable_p "$as_dir/$ac_word$ac_exec_ext"; then
-    ac_cv_prog_libxml2_found="yes"
-    echo "$as_me:$LINENO: found $as_dir/$ac_word$ac_exec_ext" >&5
-    break 2
-  fi
-done
-done
-
-  test -z "$ac_cv_prog_libxml2_found" && ac_cv_prog_libxml2_found="no"
-fi
-fi
-libxml2_found=$ac_cv_prog_libxml2_found
-if test -n "$libxml2_found"; then
-  echo "$as_me:$LINENO: result: $libxml2_found" >&5
-echo "${ECHO_T}$libxml2_found" >&6
-else
-  echo "$as_me:$LINENO: result: no" >&5
-echo "${ECHO_T}no" >&6
-fi
-
-if test $libxml2_found = yes; then
-	XML2_INCLUDES=`xml2-config --cflags`
-	XML2_LFLAGS=`xml2-config --libs`
-
-
-else
- 	echo "*** Unable to find libxml2 development files on your system."
-        echo "*** Perhaps you need to install the package libxml2-dev?"
-	exit 1
+# Modify compiler flags when debug is enabled
+if test x$enable_debug = xyes; then
+    CXXFLAGS='-DDEBUG=1 -g -O2 -Wall -Werror'
 fi
 
 # Check for curses
-echo "$as_me:$LINENO: checking for library containing wbkgdset" >&5
+if test x$enable_curses = x; then
+    echo "$as_me:$LINENO: checking for library containing wbkgdset" >&5
 echo $ECHO_N "checking for library containing wbkgdset... $ECHO_C" >&6
 if test "${ac_cv_search_wbkgdset+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
@@ -4044,9 +4014,61 @@ if test "$ac_cv_search_wbkgdset" != no; then
   test "$ac_cv_search_wbkgdset" = "none required" || LIBS="$ac_cv_search_wbkgdset $LIBS"
 
 else
-  echo "*** Unable to find ncurses on your system."; exit 1
+  echo "*** Unable to find ncurses on your system. "
+                   echo "*** Try ./configure --disable-curses or install ncurses." ; exit 1
 fi
 
+else
+    CXXFLAGS=$CXXFLAGS' -DNO_CURSES=1'
+fi
+
+# Check for libxml2
+# Extract the first word of "xml2-config", so it can be a program name with args.
+set dummy xml2-config; ac_word=$2
+echo "$as_me:$LINENO: checking for $ac_word" >&5
+echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6
+if test "${ac_cv_prog_libxml2_found+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  if test -n "$libxml2_found"; then
+  ac_cv_prog_libxml2_found="$libxml2_found" # Let the user override the test.
+else
+as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
+for as_dir in $PATH
+do
+  IFS=$as_save_IFS
+  test -z "$as_dir" && as_dir=.
+  for ac_exec_ext in '' $ac_executable_extensions; do
+  if $as_executable_p "$as_dir/$ac_word$ac_exec_ext"; then
+    ac_cv_prog_libxml2_found="yes"
+    echo "$as_me:$LINENO: found $as_dir/$ac_word$ac_exec_ext" >&5
+    break 2
+  fi
+done
+done
+
+  test -z "$ac_cv_prog_libxml2_found" && ac_cv_prog_libxml2_found="no"
+fi
+fi
+libxml2_found=$ac_cv_prog_libxml2_found
+if test -n "$libxml2_found"; then
+  echo "$as_me:$LINENO: result: $libxml2_found" >&5
+echo "${ECHO_T}$libxml2_found" >&6
+else
+  echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+fi
+
+if test $libxml2_found = yes; then
+	XML2_INCLUDES=`xml2-config --cflags`
+	XML2_LFLAGS=`xml2-config --libs`
+
+
+else
+ 	echo "*** Unable to find libxml2 development files on your system."
+        echo "*** Perhaps you need to install the package libxml2-dev?"
+	exit 1
+fi
 
 # Note: need to be in the correct order, and some are needed twice.
 # Not very pretty... Maybe someone knows how to fix this?
