Tailorized "2005-10-24 20:29:09 by johanjan" Build:
Added --enable-pydolfin flag as well as install rule for PyDOLFIN.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -310,7 +310,7 @@ ac_includes_default="\
 # include <unistd.h>
 #endif"
 
-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM mkdir_p AWK SET_MAKE am__leading_dot AMTAR am__tar am__untar MAINTAINER_MODE_TRUE MAINTAINER_MODE_FALSE MAINT CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CCDEPMODE am__fastdepCC_TRUE am__fastdepCC_FALSE CXX CXXFLAGS ac_ct_CXX CXXDEPMODE am__fastdepCXX_TRUE am__fastdepCXX_FALSE RANLIB ac_ct_RANLIB LN_S CPP EGREP PYTHON PYTHON_VERSION PYTHON_PREFIX PYTHON_EXEC_PREFIX PYTHON_PLATFORM pythondir pkgpythondir pyexecdir pkgpyexecdir PYTHON_CPPFLAGS PYTHON_LDFLAGS PYTHON_SITE_PKG PYTHON_EXTRA_LIBS SWIG SWIG_LIB SWIG_PYTHON_OPT SWIG_PYTHON_CPPFLAGS petsc_found mpi_found libxml2_found KERNEL_CFLAGS MODULE_CFLAGS DOLFIN_CFLAGS DOLFIN_LIBS LIBOBJS LTLIBOBJS'
+ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM mkdir_p AWK SET_MAKE am__leading_dot AMTAR am__tar am__untar MAINTAINER_MODE_TRUE MAINTAINER_MODE_FALSE MAINT CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CCDEPMODE am__fastdepCC_TRUE am__fastdepCC_FALSE CXX CXXFLAGS ac_ct_CXX CXXDEPMODE am__fastdepCXX_TRUE am__fastdepCXX_FALSE RANLIB ac_ct_RANLIB LN_S CPP EGREP PYTHON PYTHON_VERSION PYTHON_PREFIX PYTHON_EXEC_PREFIX PYTHON_PLATFORM pythondir pkgpythondir pyexecdir pkgpyexecdir PYTHON_CPPFLAGS PYTHON_LDFLAGS PYTHON_SITE_PKG PYTHON_EXTRA_LIBS SWIG SWIG_LIB SWIG_PYTHON_OPT SWIG_PYTHON_CPPFLAGS COMPILE_PYDOLFIN_TRUE COMPILE_PYDOLFIN_FALSE petsc_found mpi_found libxml2_found KERNEL_CFLAGS MODULE_CFLAGS DOLFIN_CFLAGS DOLFIN_LIBS LIBOBJS LTLIBOBJS'
 ac_subst_files=''
 
 # Initialize some variables set by options.
@@ -861,8 +861,9 @@ Optional Features:
   --enable-debug          Turn on debugging and warnings (this is the default)
   --enable-optimization   Turn on optimization
   --disable-curses        Compile without curses
-  --disalbe-mpi           Compile without MPI (assuming PETSc does not use
+  --disable-mpi           Compile without MPI (assuming PETSc does not use
                           MPI)
+  --enable-pydolfin       Turn on compilation of PyDOLFIN
   --disable-dependency-tracking  speeds up one-time build
   --enable-dependency-tracking   do not reject slow dependency extractors
 
@@ -1823,6 +1824,13 @@ fi;
 if test "${with_petsc_dir+set}" = set; then
   withval="$with_petsc_dir"
   PETSC_DIR=$with_petsc_dir
+fi;
+
+# Option --enable-optimization
+# Check whether --enable-pydolfin or --disable-pydolfin was given.
+if test "${enable_pydolfin+set}" = set; then
+  enableval="$enable_pydolfin"
+  enable_pydolfin=yes
 fi;
 
 # Standard tests
@@ -4362,7 +4370,7 @@ if test "${am_cv_pathless_PYTHON+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
 else
 
-	for am_cv_pathless_PYTHON in python python2 python2.4 python2.3 python2.2 python2.1 python2.0 python1.6 python1.5 none; do
+	for am_cv_pathless_PYTHON in python python2 python2.5 python2.4 python2.3 python2.2 python2.1 python2.0 python1.6 python1.5 none; do
 	  test "$am_cv_pathless_PYTHON" = none && break
 	  prog="import sys, string
 # split strings by '.' and convert to numeric.  Append some zeros
@@ -4868,6 +4876,23 @@ else
     echo "using PETSC_DIR=$PETSC_DIR"
 fi
 
+# Handle option --enable-pydolfin
+
+
+if test x$enable_pydolfin = xyes; then
+  COMPILE_PYDOLFIN_TRUE=
+  COMPILE_PYDOLFIN_FALSE='#'
+else
+  COMPILE_PYDOLFIN_TRUE='#'
+  COMPILE_PYDOLFIN_FALSE=
+fi
+
+if test x$enable_pydolfin = xyes; then
+    echo "enabling compilation of PyDOLFIN"
+else
+    echo "disabling compilation of PyDOLFIN"
+fi
+
 # Check for PETSc
 # Extract the first word of "configarch", so it can be a program name with args.
 set dummy configarch; ac_word=$2
@@ -5209,6 +5234,13 @@ if test -z "${am__fastdepCXX_TRUE}" && test -z "${am__fastdepCXX_FALSE}"; then
   { { echo "$as_me:$LINENO: error: conditional \"am__fastdepCXX\" was never defined.
 Usually this means the macro was only invoked conditionally." >&5
 echo "$as_me: error: conditional \"am__fastdepCXX\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
+if test -z "${COMPILE_PYDOLFIN_TRUE}" && test -z "${COMPILE_PYDOLFIN_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"COMPILE_PYDOLFIN\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"COMPILE_PYDOLFIN\" was never defined.
 Usually this means the macro was only invoked conditionally." >&2;}
    { (exit 1); exit 1; }; }
 fi
@@ -5866,6 +5898,8 @@ s,@SWIG@,$SWIG,;t t
 s,@SWIG_LIB@,$SWIG_LIB,;t t
 s,@SWIG_PYTHON_OPT@,$SWIG_PYTHON_OPT,;t t
 s,@SWIG_PYTHON_CPPFLAGS@,$SWIG_PYTHON_CPPFLAGS,;t t
+s,@COMPILE_PYDOLFIN_TRUE@,$COMPILE_PYDOLFIN_TRUE,;t t
+s,@COMPILE_PYDOLFIN_FALSE@,$COMPILE_PYDOLFIN_FALSE,;t t
 s,@petsc_found@,$petsc_found,;t t
 s,@mpi_found@,$mpi_found,;t t
 s,@libxml2_found@,$libxml2_found,;t t
