Update configure.ac for yet another UMFPACK location.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -20929,7 +20929,7 @@ Alternatively, you may set the environment variables UFC_CFLAGS
 and UFC_LIBS to avoid the need to call pkg-config.
 See the pkg-config man page for more details.
 
-To get pkg-config, see <http://www.freedesktop.org/software/pkgconfig>.
+To get pkg-config, see <http://pkg-config.freedesktop.org/>.
 See \`config.log' for more details." >&5
 echo "$as_me: error: The pkg-config script could not be found or is too old.  Make sure it
 is in your PATH or set the PKG_CONFIG environment variable to the full
@@ -20939,7 +20939,7 @@ Alternatively, you may set the environment variables UFC_CFLAGS
 and UFC_LIBS to avoid the need to call pkg-config.
 See the pkg-config man page for more details.
 
-To get pkg-config, see <http://www.freedesktop.org/software/pkgconfig>.
+To get pkg-config, see <http://pkg-config.freedesktop.org/>.
 See \`config.log' for more details." >&2;}
    { (exit 1); exit 1; }; }
 else
@@ -21484,7 +21484,151 @@ fi
 _ACEOF
 
                 else
-                    echo "Cannot find umfpack header files. Umfpack will be disabled"
+                    if test "${ac_cv_header_suitesparse_umfpack_h+set}" = set; then
+  { echo "$as_me:$LINENO: checking for suitesparse/umfpack.h" >&5
+echo $ECHO_N "checking for suitesparse/umfpack.h... $ECHO_C" >&6; }
+if test "${ac_cv_header_suitesparse_umfpack_h+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+fi
+{ echo "$as_me:$LINENO: result: $ac_cv_header_suitesparse_umfpack_h" >&5
+echo "${ECHO_T}$ac_cv_header_suitesparse_umfpack_h" >&6; }
+else
+  # Is the header compilable?
+{ echo "$as_me:$LINENO: checking suitesparse/umfpack.h usability" >&5
+echo $ECHO_N "checking suitesparse/umfpack.h usability... $ECHO_C" >&6; }
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+$ac_includes_default
+#include <suitesparse/umfpack.h>
+_ACEOF
+rm -f conftest.$ac_objext
+if { (ac_try="$ac_compile"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_compile") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && {
+	 test -z "$ac_cxx_werror_flag" ||
+	 test ! -s conftest.err
+       } && test -s conftest.$ac_objext; then
+  ac_header_compiler=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+	ac_header_compiler=no
+fi
+
+rm -f core conftest.err conftest.$ac_objext conftest.$ac_ext
+{ echo "$as_me:$LINENO: result: $ac_header_compiler" >&5
+echo "${ECHO_T}$ac_header_compiler" >&6; }
+
+# Is the header present?
+{ echo "$as_me:$LINENO: checking suitesparse/umfpack.h presence" >&5
+echo $ECHO_N "checking suitesparse/umfpack.h presence... $ECHO_C" >&6; }
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+#include <suitesparse/umfpack.h>
+_ACEOF
+if { (ac_try="$ac_cpp conftest.$ac_ext"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_cpp conftest.$ac_ext") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } >/dev/null && {
+	 test -z "$ac_cxx_preproc_warn_flag$ac_cxx_werror_flag" ||
+	 test ! -s conftest.err
+       }; then
+  ac_header_preproc=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+  ac_header_preproc=no
+fi
+
+rm -f conftest.err conftest.$ac_ext
+{ echo "$as_me:$LINENO: result: $ac_header_preproc" >&5
+echo "${ECHO_T}$ac_header_preproc" >&6; }
+
+# So?  What about this header?
+case $ac_header_compiler:$ac_header_preproc:$ac_cxx_preproc_warn_flag in
+  yes:no: )
+    { echo "$as_me:$LINENO: WARNING: suitesparse/umfpack.h: accepted by the compiler, rejected by the preprocessor!" >&5
+echo "$as_me: WARNING: suitesparse/umfpack.h: accepted by the compiler, rejected by the preprocessor!" >&2;}
+    { echo "$as_me:$LINENO: WARNING: suitesparse/umfpack.h: proceeding with the compiler's result" >&5
+echo "$as_me: WARNING: suitesparse/umfpack.h: proceeding with the compiler's result" >&2;}
+    ac_header_preproc=yes
+    ;;
+  no:yes:* )
+    { echo "$as_me:$LINENO: WARNING: suitesparse/umfpack.h: present but cannot be compiled" >&5
+echo "$as_me: WARNING: suitesparse/umfpack.h: present but cannot be compiled" >&2;}
+    { echo "$as_me:$LINENO: WARNING: suitesparse/umfpack.h:     check for missing prerequisite headers?" >&5
+echo "$as_me: WARNING: suitesparse/umfpack.h:     check for missing prerequisite headers?" >&2;}
+    { echo "$as_me:$LINENO: WARNING: suitesparse/umfpack.h: see the Autoconf documentation" >&5
+echo "$as_me: WARNING: suitesparse/umfpack.h: see the Autoconf documentation" >&2;}
+    { echo "$as_me:$LINENO: WARNING: suitesparse/umfpack.h:     section \"Present But Cannot Be Compiled\"" >&5
+echo "$as_me: WARNING: suitesparse/umfpack.h:     section \"Present But Cannot Be Compiled\"" >&2;}
+    { echo "$as_me:$LINENO: WARNING: suitesparse/umfpack.h: proceeding with the preprocessor's result" >&5
+echo "$as_me: WARNING: suitesparse/umfpack.h: proceeding with the preprocessor's result" >&2;}
+    { echo "$as_me:$LINENO: WARNING: suitesparse/umfpack.h: in the future, the compiler will take precedence" >&5
+echo "$as_me: WARNING: suitesparse/umfpack.h: in the future, the compiler will take precedence" >&2;}
+    ( cat <<\_ASBOX
+## ---------------------------------------------- ##
+## Report this to http://www.fenics.org/bugzilla/ ##
+## ---------------------------------------------- ##
+_ASBOX
+     ) | sed "s/^/$as_me: WARNING:     /" >&2
+    ;;
+esac
+{ echo "$as_me:$LINENO: checking for suitesparse/umfpack.h" >&5
+echo $ECHO_N "checking for suitesparse/umfpack.h... $ECHO_C" >&6; }
+if test "${ac_cv_header_suitesparse_umfpack_h+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_cv_header_suitesparse_umfpack_h=$ac_header_preproc
+fi
+{ echo "$as_me:$LINENO: result: $ac_cv_header_suitesparse_umfpack_h" >&5
+echo "${ECHO_T}$ac_cv_header_suitesparse_umfpack_h" >&6; }
+
+fi
+if test $ac_cv_header_suitesparse_umfpack_h = yes; then
+  have_umfpack_header=yes
+else
+  have_umfpack_header=no
+fi
+
+
+                    if test $have_umfpack_header = yes; then
+                        cat >>confdefs.h <<\_ACEOF
+#define HAVE_SUITESPARSE_UMFPACK_H 1
+_ACEOF
+
+                    else
+                        echo "Cannot find umfpack header files. Umfpack will be disabled"
+                    fi
                 fi
             fi
        fi
