Add test for Python development files (python2.3-dev or python2.4-dev) needed to build PyDOLFIN. This is what caused the problems for the compile bot.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -21255,6 +21255,155 @@ echo "$as_me: WARNING: cannot determine SWIG version" >&2;}
         fi
 
 
+    as_ac_Header=`echo "ac_cv_header_python$PYTHON_VERSION/Python.h" | $as_tr_sh`
+if eval "test \"\${$as_ac_Header+set}\" = set"; then
+  echo "$as_me:$LINENO: checking for python$PYTHON_VERSION/Python.h" >&5
+echo $ECHO_N "checking for python$PYTHON_VERSION/Python.h... $ECHO_C" >&6
+if eval "test \"\${$as_ac_Header+set}\" = set"; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+fi
+echo "$as_me:$LINENO: result: `eval echo '${'$as_ac_Header'}'`" >&5
+echo "${ECHO_T}`eval echo '${'$as_ac_Header'}'`" >&6
+else
+  # Is the header compilable?
+echo "$as_me:$LINENO: checking python$PYTHON_VERSION/Python.h usability" >&5
+echo $ECHO_N "checking python$PYTHON_VERSION/Python.h usability... $ECHO_C" >&6
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+$ac_includes_default
+#include <python$PYTHON_VERSION/Python.h>
+_ACEOF
+rm -f conftest.$ac_objext
+if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
+  (eval $ac_compile) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_cxx_werror_flag"			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest.$ac_objext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_header_compiler=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+ac_header_compiler=no
+fi
+rm -f conftest.err conftest.$ac_objext conftest.$ac_ext
+echo "$as_me:$LINENO: result: $ac_header_compiler" >&5
+echo "${ECHO_T}$ac_header_compiler" >&6
+
+# Is the header present?
+echo "$as_me:$LINENO: checking python$PYTHON_VERSION/Python.h presence" >&5
+echo $ECHO_N "checking python$PYTHON_VERSION/Python.h presence... $ECHO_C" >&6
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+#include <python$PYTHON_VERSION/Python.h>
+_ACEOF
+if { (eval echo "$as_me:$LINENO: \"$ac_cpp conftest.$ac_ext\"") >&5
+  (eval $ac_cpp conftest.$ac_ext) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } >/dev/null; then
+  if test -s conftest.err; then
+    ac_cpp_err=$ac_cxx_preproc_warn_flag
+    ac_cpp_err=$ac_cpp_err$ac_cxx_werror_flag
+  else
+    ac_cpp_err=
+  fi
+else
+  ac_cpp_err=yes
+fi
+if test -z "$ac_cpp_err"; then
+  ac_header_preproc=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+  ac_header_preproc=no
+fi
+rm -f conftest.err conftest.$ac_ext
+echo "$as_me:$LINENO: result: $ac_header_preproc" >&5
+echo "${ECHO_T}$ac_header_preproc" >&6
+
+# So?  What about this header?
+case $ac_header_compiler:$ac_header_preproc:$ac_cxx_preproc_warn_flag in
+  yes:no: )
+    { echo "$as_me:$LINENO: WARNING: python$PYTHON_VERSION/Python.h: accepted by the compiler, rejected by the preprocessor!" >&5
+echo "$as_me: WARNING: python$PYTHON_VERSION/Python.h: accepted by the compiler, rejected by the preprocessor!" >&2;}
+    { echo "$as_me:$LINENO: WARNING: python$PYTHON_VERSION/Python.h: proceeding with the compiler's result" >&5
+echo "$as_me: WARNING: python$PYTHON_VERSION/Python.h: proceeding with the compiler's result" >&2;}
+    ac_header_preproc=yes
+    ;;
+  no:yes:* )
+    { echo "$as_me:$LINENO: WARNING: python$PYTHON_VERSION/Python.h: present but cannot be compiled" >&5
+echo "$as_me: WARNING: python$PYTHON_VERSION/Python.h: present but cannot be compiled" >&2;}
+    { echo "$as_me:$LINENO: WARNING: python$PYTHON_VERSION/Python.h:     check for missing prerequisite headers?" >&5
+echo "$as_me: WARNING: python$PYTHON_VERSION/Python.h:     check for missing prerequisite headers?" >&2;}
+    { echo "$as_me:$LINENO: WARNING: python$PYTHON_VERSION/Python.h: see the Autoconf documentation" >&5
+echo "$as_me: WARNING: python$PYTHON_VERSION/Python.h: see the Autoconf documentation" >&2;}
+    { echo "$as_me:$LINENO: WARNING: python$PYTHON_VERSION/Python.h:     section \"Present But Cannot Be Compiled\"" >&5
+echo "$as_me: WARNING: python$PYTHON_VERSION/Python.h:     section \"Present But Cannot Be Compiled\"" >&2;}
+    { echo "$as_me:$LINENO: WARNING: python$PYTHON_VERSION/Python.h: proceeding with the preprocessor's result" >&5
+echo "$as_me: WARNING: python$PYTHON_VERSION/Python.h: proceeding with the preprocessor's result" >&2;}
+    { echo "$as_me:$LINENO: WARNING: python$PYTHON_VERSION/Python.h: in the future, the compiler will take precedence" >&5
+echo "$as_me: WARNING: python$PYTHON_VERSION/Python.h: in the future, the compiler will take precedence" >&2;}
+    (
+      cat <<\_ASBOX
+## -------------------------------- ##
+## Report this to dolfin@fenics.org ##
+## -------------------------------- ##
+_ASBOX
+    ) |
+      sed "s/^/$as_me: WARNING:     /" >&2
+    ;;
+esac
+echo "$as_me:$LINENO: checking for python$PYTHON_VERSION/Python.h" >&5
+echo $ECHO_N "checking for python$PYTHON_VERSION/Python.h... $ECHO_C" >&6
+if eval "test \"\${$as_ac_Header+set}\" = set"; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  eval "$as_ac_Header=\$ac_header_preproc"
+fi
+echo "$as_me:$LINENO: result: `eval echo '${'$as_ac_Header'}'`" >&5
+echo "${ECHO_T}`eval echo '${'$as_ac_Header'}'`" >&6
+
+fi
+if test `eval echo '${'$as_ac_Header'}'` = yes; then
+  have_python_dev=yes
+else
+  have_python_dev=no
+fi
+
+
+    if test $have_python_dev = no; then
+       echo "*** Cannot find Python development files on your system."
+       echo "*** Perhaps you need to install the package python$PYTHON_VERSION-dev?"
+       exit 1
+    fi
 
 
 
