Tailorized "2004-11-30 04:07:05 by logg" Added PETSc dependency in preparation for some PETSc benchmarks. If benchmarks are favorable, we'll start moving towards making PETSc the base of linear algebra in DOLFIN.
Please test and see if you can get it to compile. Everything needed
is available in Debian, and the configure script should tell you
what you need to install.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -310,7 +310,7 @@ ac_includes_default="\
 # include <unistd.h>
 #endif"
 
-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO SET_MAKE MAINTAINER_MODE_TRUE MAINTAINER_MODE_FALSE MAINT CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT CXX CXXFLAGS ac_ct_CXX RANLIB ac_ct_RANLIB AWK LN_S CPP EGREP libxml2_found XML2_INCLUDES XML2_LFLAGS MODULE_INCLUDES MAIN_INCLUDES DOLFIN_LFLAGS LIBOBJS LTLIBOBJS'
+ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO SET_MAKE MAINTAINER_MODE_TRUE MAINTAINER_MODE_FALSE MAINT CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT CXX CXXFLAGS ac_ct_CXX RANLIB ac_ct_RANLIB AWK LN_S CPP EGREP petsc_found PETSC_ARCH PETSC_DIR BOPT PETSC_CFLAGS mpi_found libxml2_found KERNEL_CFLAGS MAIN_CFLAGS DOLFIN_LIBS LIBOBJS LTLIBOBJS'
 ac_subst_files=''
 
 # Initialize some variables set by options.
@@ -861,7 +861,6 @@ Optional Features:
   --enable-debug          Turn on debugging and warnings
   --enable-optimization   Turn on optimization
   --disable-curses        Compile without curses
-  --enable-bmp            support loading BMP images default=yes
 
 Some influential environment variables:
   CC          C compiler command
@@ -1325,6 +1324,7 @@ ac_compiler_gnu=$ac_cv_c_compiler_gnu
 
 
 # Init automake
+am__api_version="1.4"
 ac_aux_dir=
 for ac_dir in $srcdir $srcdir/.. $srcdir/../..; do
   if test -f $ac_dir/install-sh; then
@@ -1530,17 +1530,17 @@ fi
 
 
 missing_dir=`cd $ac_aux_dir && pwd`
-echo "$as_me:$LINENO: checking for working aclocal" >&5
-echo $ECHO_N "checking for working aclocal... $ECHO_C" >&6
+echo "$as_me:$LINENO: checking for working aclocal-${am__api_version}" >&5
+echo $ECHO_N "checking for working aclocal-${am__api_version}... $ECHO_C" >&6
 # Run test in a subshell; some versions of sh will print an error if
 # an executable is not found, even if stderr is redirected.
 # Redirect stdin to placate older versions of autoconf.  Sigh.
-if (aclocal --version) < /dev/null > /dev/null 2>&1; then
-   ACLOCAL=aclocal
+if (aclocal-${am__api_version} --version) < /dev/null > /dev/null 2>&1; then
+   ACLOCAL=aclocal-${am__api_version}
    echo "$as_me:$LINENO: result: found" >&5
 echo "${ECHO_T}found" >&6
 else
-   ACLOCAL="$missing_dir/missing aclocal"
+   ACLOCAL="$missing_dir/missing aclocal-${am__api_version}"
    echo "$as_me:$LINENO: result: missing" >&5
 echo "${ECHO_T}missing" >&6
 fi
@@ -1560,17 +1560,17 @@ else
 echo "${ECHO_T}missing" >&6
 fi
 
-echo "$as_me:$LINENO: checking for working automake" >&5
-echo $ECHO_N "checking for working automake... $ECHO_C" >&6
+echo "$as_me:$LINENO: checking for working automake-${am__api_version}" >&5
+echo $ECHO_N "checking for working automake-${am__api_version}... $ECHO_C" >&6
 # Run test in a subshell; some versions of sh will print an error if
 # an executable is not found, even if stderr is redirected.
 # Redirect stdin to placate older versions of autoconf.  Sigh.
-if (automake --version) < /dev/null > /dev/null 2>&1; then
-   AUTOMAKE=automake
+if (automake-${am__api_version} --version) < /dev/null > /dev/null 2>&1; then
+   AUTOMAKE=automake-${am__api_version}
    echo "$as_me:$LINENO: result: found" >&5
 echo "${ECHO_T}found" >&6
 else
-   AUTOMAKE="$missing_dir/missing automake"
+   AUTOMAKE="$missing_dir/missing automake-${am__api_version}"
    echo "$as_me:$LINENO: result: missing" >&5
 echo "${ECHO_T}missing" >&6
 fi
@@ -1654,18 +1654,7 @@ if test "${enable_curses+set}" = set; then
   enable_curses=no
 fi;
 
-# Check whether --enable-bmp or --disable-bmp was given.
-if test "${enable_bmp+set}" = set; then
-  enableval="$enable_bmp"
-
-else
-  enable_bmp=yes
-fi;
-if test x$enable_bmp = xyes; then
-    CFLAGS="$CFLAGS -DLOAD_BMP"
-fi
-
-# Checks for programs
+# Standard tests
 ac_ext=c
 ac_cpp='$CPP $CPPFLAGS'
 ac_compile='$CC -c $CFLAGS $CPPFLAGS conftest.$ac_ext >&5'
@@ -3152,8 +3141,6 @@ echo "${ECHO_T}no, using $LN_S" >&6
 fi
 
 
-# Checks for typedefs, structures, and compiler characteristics.
-
 echo "$as_me:$LINENO: checking for an ANSI C-conforming const" >&5
 echo $ECHO_N "checking for an ANSI C-conforming const... $ECHO_C" >&6
 if test "${ac_cv_c_const+set}" = set; then
@@ -3882,18 +3869,18 @@ _ACEOF
 fi
 
 
-# Modify compiler flags when debug is enabled
+# Handle option --enable-debug
 if test x$enable_debug = xyes; then
     CXXFLAGS='-DDEBUG=1 -g -O2 -Wall -Werror -pedantic -ansi -std=c++98'
 fi
 
-# Modify compiler flags when optimization is enabled
+# Handle option --enable-optimization
 if test x$enable_optimization = xyes; then
     CXXFLAGS='-O3 -Wall -Werror -pedantic -ansi -std=c++98'
 fi
 
-# Check for curses
-if test x$enable_curses = x; then
+# Handle option --disable-curses
+if test x$disable_curses = x; then
     echo "$as_me:$LINENO: checking for library containing wbkgdset" >&5
 echo $ECHO_N "checking for library containing wbkgdset... $ECHO_C" >&6
 if test "${ac_cv_search_wbkgdset+set}" = set; then
@@ -4021,8 +4008,110 @@ else
                    echo "*** Try ./configure --disable-curses or install ncurses." ; exit 1
 fi
 
+    CURSES_CFLAGS=''
+    CURSES_LIBS='-lncurses'
 else
-    CXXFLAGS=$CXXFLAGS' -DNO_CURSES=1'
+    CURSES_CFLAGS='-DNO_CURSES=1'
+    CURSES_LIBS=''
+fi
+
+# Check for PETSc
+# Extract the first word of "petscarch", so it can be a program name with args.
+set dummy petscarch; ac_word=$2
+echo "$as_me:$LINENO: checking for $ac_word" >&5
+echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6
+if test "${ac_cv_prog_petsc_found+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  if test -n "$petsc_found"; then
+  ac_cv_prog_petsc_found="$petsc_found" # Let the user override the test.
+else
+as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
+for as_dir in $PATH
+do
+  IFS=$as_save_IFS
+  test -z "$as_dir" && as_dir=.
+  for ac_exec_ext in '' $ac_executable_extensions; do
+  if $as_executable_p "$as_dir/$ac_word$ac_exec_ext"; then
+    ac_cv_prog_petsc_found="yes"
+    echo "$as_me:$LINENO: found $as_dir/$ac_word$ac_exec_ext" >&5
+    break 2
+  fi
+done
+done
+
+  test -z "$ac_cv_prog_petsc_found" && ac_cv_prog_petsc_found="no"
+fi
+fi
+petsc_found=$ac_cv_prog_petsc_found
+if test -n "$petsc_found"; then
+  echo "$as_me:$LINENO: result: $petsc_found" >&5
+echo "${ECHO_T}$petsc_found" >&6
+else
+  echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+fi
+
+if test $petsc_found = yes; then
+    # FIXME: Do correct test
+    PETSC_ARCH=`petscarch`
+    PETSC_DIR='/usr/lib/petsc'
+    BOPT='O_c++'
+    PETSC_CFLAGS="-DPETSC_DIR=$PETSC_DIR -DPETSC_ARCH=$PETSC_ARCH -DPETSC_USE_BOPT_O -DPETSC_USE_EXTERN_CXX"
+
+
+
+
+else
+    echo "*** Unable to find PETSc on your system."
+    echo "*** Perhaps you need to install the package petsc-dev?"
+    exit 1
+fi
+
+# Check for MPI (needed by PETSc)
+# Extract the first word of "mpirun", so it can be a program name with args.
+set dummy mpirun; ac_word=$2
+echo "$as_me:$LINENO: checking for $ac_word" >&5
+echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6
+if test "${ac_cv_prog_mpi_found+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  if test -n "$mpi_found"; then
+  ac_cv_prog_mpi_found="$mpi_found" # Let the user override the test.
+else
+as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
+for as_dir in $PATH
+do
+  IFS=$as_save_IFS
+  test -z "$as_dir" && as_dir=.
+  for ac_exec_ext in '' $ac_executable_extensions; do
+  if $as_executable_p "$as_dir/$ac_word$ac_exec_ext"; then
+    ac_cv_prog_mpi_found="yes"
+    echo "$as_me:$LINENO: found $as_dir/$ac_word$ac_exec_ext" >&5
+    break 2
+  fi
+done
+done
+
+  test -z "$ac_cv_prog_mpi_found" && ac_cv_prog_mpi_found="no"
+fi
+fi
+mpi_found=$ac_cv_prog_mpi_found
+if test -n "$mpi_found"; then
+  echo "$as_me:$LINENO: result: $mpi_found" >&5
+echo "${ECHO_T}$mpi_found" >&6
+else
+  echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+fi
+
+if test $mpi_found = yes; then
+    # FIXME: Do correct test
+    MPI_CFLAGS='-I/usr/include/mpi'
+else
+    echo "*** Unable to find MPI on your system."
+    echo "*** Perhaps you need to install the package mpich?"
+    exit 1
 fi
 
 # Check for libxml2
@@ -4063,21 +4152,16 @@ echo "${ECHO_T}no" >&6
 fi
 
 if test $libxml2_found = yes; then
-	XML2_INCLUDES=`xml2-config --cflags`
-	XML2_LFLAGS=`xml2-config --libs`
-
-
+    XML2_CFLAGS=`xml2-config --cflags`
+    XML2_LIBS=`xml2-config --libs`
 else
- 	echo "*** Unable to find libxml2 development files on your system."
-        echo "*** Perhaps you need to install the package libxml2-dev?"
-	exit 1
+    echo "*** Unable to find libxml2 development files on your system."
+    echo "*** Perhaps you need to install the package libxml2-dev?"
+    exit 1
 fi
 
-# Note: need to be in the correct order, and some are needed twice.
-# Not very pretty... Maybe someone knows how to fix this?
-#DOLFIN_KERNEL="ode io mesh fem element mesh io fem form quadrature map la math common settings log settings common main ode"
+# List of DOLFIN kernel modules
 DOLFIN_KERNEL="common element fem form function io la log main map math mesh ode quadrature settings common"
-DOLFIN_KERNEL="$DOLFIN_KERNEL $DOLFIN_KERNEL $DOLFIN_KERNEL $DOLFIN_KERNEL"
 
 # Find modules
 cd src/modules
@@ -4085,39 +4169,40 @@ cd src/modules
 cd ../..
 DOLFIN_MODULES=""
 for l in `cat src/modules/modules.list | grep -v "#"`; do
-	DOLFIN_MODULES="$DOLFIN_MODULES$l "
+    DOLFIN_MODULES="$DOLFIN_MODULES$l "
 done
 
-# Generate include path for modules (including kernel code)
-MODULE_INCLUDES=""
+# Generate include path for kernel
+KERNEL_CFLAGS=""
 DOLFIN_MAIN="main"
 DIRS="$DOLFIN_MAIN $DOLFIN_KERNEL"
 for f in $DIRS; do
-	MODULE_INCLUDES="$MODULE_INCLUDES-I\$(top_builddir)/src/kernel/$f "
+    KERNEL_CFLAGS="$KERNEL_CFLAGS-I\$(top_builddir)/src/kernel/$f "
 done
+KERNEL_CFLAGS="$KERNEL_CFLAGS $CURSES_CFLAGS $PETSC_CFLAGS $MPI_CFLAGS $XML2_CFLAGS"
 
 
 # Generate include path for main (including also module code)
-MAIN_INCLUDES=""
+MAIN_CFLAGS=""
 DIRS="$DOLFIN_MODULES"
 for f in $DIRS; do
-	MAIN_INCLUDES="$MAIN_INCLUDES-I\$(top_builddir)/src/modules/$f "
+    MAIN_CFLAGS="$MAIN_CFLAGS-I\$(top_builddir)/src/modules/$f "
 done
-MAIN_INCLUDES="$MODULE_INCLUDES $MAIN_INCLUDES"
+MAIN_CFLAGS="$KERNEL_CFLAGS $MAIN_CFLAGS"
 
 
 # Generate library list for linking in the correct order.
-DOLFIN_LFLAGS=""
-DIRS="$DOLFIN_MAIN $DOLFIN_MODULES $DOLFIN_KERNEL"
+# FIXME: Not very pretty to list the libraries multiple times
+DOLFIN_LIBS=""
+DIRS="$DOLFIN_MAIN $DOLFIN_MODULES $DOLFIN_KERNEL $DOLFIN_KERNEL $DOLFIN_KERNEL $DOLFIN_KERNEL"
 for f in $DIRS; do
-	DOLFIN_LFLAGS="$DOLFIN_LFLAGS-ldolfin-$f "
+    DOLFIN_LIBS="$DOLFIN_LIBS-ldolfin-$f "
 done
-
-
-# Seems to be needed for CXXFLAGS to get to src/config
+DOLFIN_LIBS="$DOLFIN_LIBS $CURSES_LIBS $XML2_LIBS"
 
 
 # Export variables to makefiles
+
 
 
 
@@ -4850,12 +4935,16 @@ s,@AWK@,$AWK,;t t
 s,@LN_S@,$LN_S,;t t
 s,@CPP@,$CPP,;t t
 s,@EGREP@,$EGREP,;t t
+s,@petsc_found@,$petsc_found,;t t
+s,@PETSC_ARCH@,$PETSC_ARCH,;t t
+s,@PETSC_DIR@,$PETSC_DIR,;t t
+s,@BOPT@,$BOPT,;t t
+s,@PETSC_CFLAGS@,$PETSC_CFLAGS,;t t
+s,@mpi_found@,$mpi_found,;t t
 s,@libxml2_found@,$libxml2_found,;t t
-s,@XML2_INCLUDES@,$XML2_INCLUDES,;t t
-s,@XML2_LFLAGS@,$XML2_LFLAGS,;t t
-s,@MODULE_INCLUDES@,$MODULE_INCLUDES,;t t
-s,@MAIN_INCLUDES@,$MAIN_INCLUDES,;t t
-s,@DOLFIN_LFLAGS@,$DOLFIN_LFLAGS,;t t
+s,@KERNEL_CFLAGS@,$KERNEL_CFLAGS,;t t
+s,@MAIN_CFLAGS@,$MAIN_CFLAGS,;t t
+s,@DOLFIN_LIBS@,$DOLFIN_LIBS,;t t
 s,@LIBOBJS@,$LIBOBJS,;t t
 s,@LTLIBOBJS@,$LTLIBOBJS,;t t
 CEOF
